version: '3.4'

services:
  readingisgood.web:
    image: ${DOCKER_REGISTRY-}readingisgoodweb
    build:
      context: .
      dockerfile: ReadingIsGood.Web/Dockerfile

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=vV5r9tn0M4@
      - ACCEPT_EULA=Y
    ports:
      - "1450:1433"